# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import resolution_pb2 as resolution__pb2


class SuperResolutionGRPCStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/maum.brain.resolution.SuperResolutionGRPC/Upload',
                request_serializer=resolution__pb2.FileChunk.SerializeToString,
                response_deserializer=resolution__pb2.UploadStatus.FromString,
                )
        self.CheckProcess = channel.unary_unary(
                '/maum.brain.resolution.SuperResolutionGRPC/CheckProcess',
                request_serializer=resolution__pb2.KeyMessage.SerializeToString,
                response_deserializer=resolution__pb2.ProcessStatus.FromString,
                )
        self.Download = channel.unary_stream(
                '/maum.brain.resolution.SuperResolutionGRPC/Download',
                request_serializer=resolution__pb2.KeyMessage.SerializeToString,
                response_deserializer=resolution__pb2.FileChunk.FromString,
                )


class SuperResolutionGRPCServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckProcess(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperResolutionGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=resolution__pb2.FileChunk.FromString,
                    response_serializer=resolution__pb2.UploadStatus.SerializeToString,
            ),
            'CheckProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckProcess,
                    request_deserializer=resolution__pb2.KeyMessage.FromString,
                    response_serializer=resolution__pb2.ProcessStatus.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=resolution__pb2.KeyMessage.FromString,
                    response_serializer=resolution__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maum.brain.resolution.SuperResolutionGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuperResolutionGRPC(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/maum.brain.resolution.SuperResolutionGRPC/Upload',
            resolution__pb2.FileChunk.SerializeToString,
            resolution__pb2.UploadStatus.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maum.brain.resolution.SuperResolutionGRPC/CheckProcess',
            resolution__pb2.KeyMessage.SerializeToString,
            resolution__pb2.ProcessStatus.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/maum.brain.resolution.SuperResolutionGRPC/Download',
            resolution__pb2.KeyMessage.SerializeToString,
            resolution__pb2.FileChunk.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
